//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parser
{
    using System;
    using System.Collections.Generic;
    
    public partial class statistica
    {
        public int id { get; set; }
        public int userid { get; set; }
        public System.DateTime data { get; set; }
        public int countR { get; set; }
        public int countS { get; set; }
        public int countMail { get; set; }
        public int countSkype { get; set; }
        public int countICQ { get; set; }
        public string request { get; set; }
    }
}
